version: '3'

services:
  db:
    image: mariadb:10.6.4-focal
    restart: always
    env_file: .env
    volumes: 
      - dbdata:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - ./init/migrate.sh:/docker-entrypoint-initdb.d/zzmigrate.sh # 'zz' - for correct (alphabetical) order (script after dump)
    ports:
      - "127.0.0.1:template_db_port:3306"

  wordpress:
    depends_on: 
      - db
    image: wordpress:6.4.1-apache
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "127.0.0.1:template_wp_port:80"

volumes:
  dbdata:
